"""add collection feature

Revision ID: 26e53c9dd214
Revises: 9f030ba00ca3
Create Date: 2026-03-25 09:30:54.324649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26e53c9dd214'
down_revision = '9f030ba00ca3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_binder', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlighted_card_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_collections_highlighted_card_id', 'cards', ['highlighted_card_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_collections_highlighted_card_id', type_='foreignkey')
        batch_op.drop_column('highlighted_card_id')

    with op.batch_alter_table('collection_cards', schema=None) as batch_op:
        batch_op.drop_column('is_binder')

    # ### end Alembic commands ###
