"""Initial schema

Revision ID: cd6be5ecb366
Revises: 
Create Date: 2026-03-16 14:00:02.000387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6be5ecb366'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('page_shape', sa.String(), nullable=True),
    sa.Column('nr_pages', sa.Integer(), nullable=True),
    sa.Column('restrictions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type_1', sa.String(), nullable=True),
    sa.Column('type_2', sa.String(), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.Column('evo_line', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('nr_official_cards', sa.Integer(), nullable=True),
    sa.Column('nr_total_cards', sa.Integer(), nullable=True),
    sa.Column('series_name', sa.String(), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('symbol_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('super_type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('set_code', sa.String(), nullable=False),
    sa.Column('set_number', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('norm_rarity', sa.String(), nullable=True),
    sa.Column('norm_rarity_code', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('hd_image_url', sa.String(), nullable=True),
    sa.Column('flavor', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['set_code'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_energy_types',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('energy_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'energy_type')
    )
    op.create_table('card_pokedex_numbers',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('pokedex_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['pokedex_number'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'pokedex_number')
    )
    op.create_table('card_sub_types',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('sub_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('card_id', 'sub_type')
    )
    op.create_table('slots',
    sa.Column('binder_id', sa.String(), nullable=False),
    sa.Column('binder_position', sa.Float(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.String(), nullable=True),
    sa.Column('reserved_card_id', sa.String(), nullable=True),
    sa.Column('card_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['binder_id'], ['binders.id'], ),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['reserved_card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('binder_id', 'binder_position')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slots')
    op.drop_table('card_sub_types')
    op.drop_table('card_pokedex_numbers')
    op.drop_table('card_energy_types')
    op.drop_table('cards')
    op.drop_table('sets')
    op.drop_table('pokemon')
    op.drop_table('binders')
    # ### end Alembic commands ###
