"""add partner status

Revision ID: d00db8759a84
Revises: 26e53c9dd214
Create Date: 2026-03-25 10:22:24.370541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00db8759a84'
down_revision = '26e53c9dd214'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card_status', schema=None) as batch_op:
        batch_op.drop_column('partner')

    # ### end Alembic commands ###
