"""empty message

Revision ID: d242f240f793
Revises: cd6be5ecb366
Create Date: 2026-03-16 18:03:55.117441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd242f240f793'
down_revision = 'cd6be5ecb366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('copies_owned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.drop_column('card_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_status', sa.VARCHAR(), nullable=True))

    op.drop_table('collection')
    # ### end Alembic commands ###
